# Generated by Django 6.1 on 2026-08-20 09:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50, unique=True, verbose_name='идентификатор')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('icon', models.CharField(max_length=10, verbose_name='иконка')),
                ('achievement_type', models.CharField(choices=[('games_played', 'Игры'), ('correct_answers', 'Правильные ответы'), ('streak', 'Серия побед'), ('perfect_game', 'Идеальная игра'), ('points', 'Очки'), ('level', 'Уровень')], max_length=20, verbose_name='тип')),
                ('requirement', models.PositiveIntegerField(verbose_name='порог')),
                ('is_rare', models.BooleanField(default=False, verbose_name='редкое')),
            ],
            options={
                'verbose_name': 'достижение',
                'verbose_name_plural': 'достижения',
                'ordering': ['requirement'],
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='очки')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='уровень')),
                ('games_played', models.PositiveIntegerField(default=0, verbose_name='игр сыграно')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name='правильных ответов')),
                ('total_answers', models.PositiveIntegerField(default=0, verbose_name='всего ответов')),
                ('best_streak', models.PositiveIntegerField(default=0, verbose_name='лучшая серия')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='текущая серия')),
                ('lives', models.PositiveSmallIntegerField(default=5, verbose_name='жизни')),
                ('last_life_refill', models.DateTimeField(default=django.utils.timezone.now, verbose_name='последнее пополнение жизней')),
                ('last_played_at', models.DateTimeField(blank=True, null=True, verbose_name='последняя игра')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлён')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_profile', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'профиль игрока',
                'verbose_name_plural': 'профили игроков',
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('win', 'Победа'), ('loss', 'Проигрыш'), ('perfect', 'Идеально')], max_length=7, verbose_name='результат')),
                ('correct_answers', models.PositiveSmallIntegerField(verbose_name='правильных')),
                ('total_answers', models.PositiveSmallIntegerField(verbose_name='всего')),
                ('points_earned', models.PositiveIntegerField(default=0, verbose_name='очки')),
                ('played_at', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.category', verbose_name='категория')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='progress.playerprofile', verbose_name='игрок')),
            ],
            options={
                'verbose_name': 'сессия игры',
                'verbose_name_plural': 'сессии игр',
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='разблокировано')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.achievement', verbose_name='достижение')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='progress.playerprofile', verbose_name='игрок')),
            ],
            options={
                'verbose_name': 'достижение игрока',
                'verbose_name_plural': 'достижения игроков',
                'unique_together': {('player', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='DailyBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True, verbose_name='дата получения')),
                ('bonus_amount', models.PositiveIntegerField(default=50, verbose_name='сумма')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_bonuses', to='progress.playerprofile', verbose_name='игрок')),
            ],
            options={
                'verbose_name': 'ежедневный бонус',
                'verbose_name_plural': 'ежедневные бонусы',
                'unique_together': {('player',)},
            },
        ),
    ]
