// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }



  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl3C8krC9E9UCZEkgwPAAVfHEQgNdL-Yc',
    appId: '1:916826097534:web:bc986bdf84b0e59c57552f',
    messagingSenderId: '916826097534',
    projectId: 'quizzy-d108d',
    authDomain: 'quizzy-d108d.firebaseapp.com',
    storageBucket: 'quizzy-d108d.firebasestorage.app',
    measurementId: 'G-31CR2CGZEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuV5f9HqnHL_hq4257zgK717QS-KEJVgk',
    appId: '1:916826097534:android:683f75a8f3fc42c657552f',
    messagingSenderId: '916826097534',
    projectId: 'quizzy-d108d',
    storageBucket: 'quizzy-d108d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRZnPTFlL1PmRgueDvczgTqyz7sq9g6NA',
    appId: '1:916826097534:ios:0bf466b154c31b8257552f',
    messagingSenderId: '916826097534',
    projectId: 'quizzy-d108d',
    storageBucket: 'quizzy-d108d.firebasestorage.app',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRZnPTFlL1PmRgueDvczgTqyz7sq9g6NA',
    appId: '1:916826097534:ios:0bf466b154c31b8257552f',
    messagingSenderId: '916826097534',
    projectId: 'quizzy-d108d',
    storageBucket: 'quizzy-d108d.firebasestorage.app',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl3C8krC9E9UCZEkgwPAAVfHEQgNdL-Yc',
    appId: '1:916826097534:web:cb781af53d7e4ee057552f',
    messagingSenderId: '916826097534',
    projectId: 'quizzy-d108d',
    authDomain: 'quizzy-d108d.firebaseapp.com',
    storageBucket: 'quizzy-d108d.firebasestorage.app',
    measurementId: 'G-ZG80Q1Z9EZ',
  );
}
