# Generated by Django 6.1 on 2026-08-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.URLField(
                blank=True, default="", verbose_name="URL изображения"
            ),
        ),
    ]
